runfile('C:/Users/DPM/.spyder-py3/multi2 (1).py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/sem.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/exam.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/exam1.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/untitled15.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/fb1.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/vowel.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/vowel.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/bank.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/vow2.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/vowel.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/sp.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/swap.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/l1.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/rev.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/exam2.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/loan1.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/hms1.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/lms (1).py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/bank.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/car.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/rain1.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/car.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/101.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/lp.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/attendnce.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/lp.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/car.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/62.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/num1.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/vh.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/sum.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/split.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/upper.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/lower.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/df15.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/d14.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/df.8.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/df.11.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/rain1.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/rs2.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/hack2.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/fb1.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/multi2 (1).py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/sem.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/exam.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/untitled15.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/exam2.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/rain1.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/n11.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/mi.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/rain1.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/rs2.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/rain1.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/exam2.py', wdir='C:/Users/DPM/.spyder-py3')

## ---(Sun Dec 29 21:17:51 2019)---
runfile('C:/Users/DPM/.spyder-py3/untitled15.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/lp.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/car.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/lp.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/rs3.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/multi2 (1).py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/dfe81.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/fb1.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/hack2.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/rs2.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/realstate1.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/rain1.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/p-c.py', wdir='C:/Users/DPM/.spyder-py3')

## ---(Tue Apr 14 18:18:52 2020)---
runfile('C:/Users/DPM/.spyder-py3/p-c.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/car.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/mus.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/p1.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/p2.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/p3.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/p4.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/p5.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/p2.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/p4.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/p2.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/p3.py', wdir='C:/Users/DPM/.spyder-py3')
runfile('C:/Users/DPM/.spyder-py3/p4.py', wdir='C:/Users/DPM/.spyder-py3')

## ---(Wed May  6 12:44:45 2020)---
runfile('C:/Users/DPM/.spyder-py3/untitled1234.py', wdir='C:/Users/DPM/.spyder-py3')

## ---(Thu Jun  4 22:03:11 2020)---
runfile('C:/Users/DPM/.spyder-py3/p5.py', wdir='C:/Users/DPM/.spyder-py3')
57
65
4
5
TT


4
44
4